version: '3'
services:
  forkthis-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forkthis-backend
    ports:
      - "3040:3040"  
    depends_on:
      - mongo-db  

  mongo-db:
    image: mongo:latest 
    container_name: mongo-container-forkthis
    ports:
      - "27018:27017"  
    volumes:
      - mongo-data:/data/db  

volumes:
  mongo-data:
    name: mongo-data-forkthis
    driver: local
